language: rust

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - ruby

rust:
  - nightly

os:
  - linux
  - osx
  
matrix:
  allow_failures:
    - os: osx

cache: cargo

before_script:
  - rustup component add rust-src llvm-tools-preview
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)
  - (test -x $HOME/.cargo/bin/cargo-objcopy || cargo install cargo-binutils)
  - cargo install-update -a

script:
  - ruby utils/make_all.rb
