name: Spelling

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Spelling

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install misspell and check
      run: |
        curl -L -o ./install-misspell.sh https://git.io/misspell
        sh ./install-misspell.sh -b ~/bin
        ~/bin/misspell .
