name: Unit-Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'utils/**'
      - 'doc/**'
      - 'docker/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'utils/**'
      - 'doc/**'
      - 'docker/**'
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.x
    - name: Set up Rust nightly
      run: |
          rustup self update
          rustup toolchain install nightly --component rust-src llvm-tools-preview
          rustup default nightly
          cargo install cargo-xbuild cargo-binutils
    - name: Make all
      run: |
        ruby utils/test_unit_all.rb
